// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh5oBCn_MT8_jKa6utGsXrUr21fCCcmkI',
    appId: '1:524180079517:web:7f14ff4337c12eaafce574',
    messagingSenderId: '524180079517',
    projectId: 'brain-wave-e0b54',
    authDomain: 'brain-wave-e0b54.firebaseapp.com',
    storageBucket: 'brain-wave-e0b54.appspot.com',
    measurementId: 'G-7EPL8NZWEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB0RH8ko9jEbD-MCFP1V4dN0yqw-1UNSM',
    appId: '1:524180079517:android:082a291d801bd48afce574',
    messagingSenderId: '524180079517',
    projectId: 'brain-wave-e0b54',
    storageBucket: 'brain-wave-e0b54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAz7QxAA8aBX96T1cH-wkVLik_sJpZGCs',
    appId: '1:524180079517:ios:1f71f9c9166d50c7fce574',
    messagingSenderId: '524180079517',
    projectId: 'brain-wave-e0b54',
    storageBucket: 'brain-wave-e0b54.appspot.com',
    iosBundleId: 'com.example.brainWave2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAz7QxAA8aBX96T1cH-wkVLik_sJpZGCs',
    appId: '1:524180079517:ios:1f71f9c9166d50c7fce574',
    messagingSenderId: '524180079517',
    projectId: 'brain-wave-e0b54',
    storageBucket: 'brain-wave-e0b54.appspot.com',
    iosBundleId: 'com.example.brainWave2',
  );
}
